name: Docs
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    environment: release
    steps:
      # actions/checkout@v5.0.1
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
        with:
          persist-credentials: false
      # actions/setup-python@v6.2.0
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
      - name: Install Sphinx
        run: |
          pip install sphinx sphinx-rtd-theme sphinx-design sphinx-copybutton
      - name: Build documentation
        run: |
          sphinx-build doc _build
      - name: Set CNAME if in public repo
        id: cname
        run: |
          if [ "${{ github.repository }}" = "erbsland-dev/erbsland-sphinx-ansi" ]; then
            echo "CNAME=sphinx-ansi.erbsland.dev" >> $GITHUB_ENV
          fi
      - name: Deploy
        # peaceiris/actions-gh-pages@v4.1.0
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
          cname: ${{ env.CNAME }}
